# Prerequisite:
#   GOOGLE_CREDENTIALS repository secret containing GCP service account json should be set up.
#   Corresponding servince account requires following roles:
#   - Artifact Registry Repository Administrator: to be able to upload docker images to Artifact Registry
#   - Cloud Run developer: to be able to deploy a new revision to Cloud Run
#   - Service Account User: to be able to deploy a new revision to Cloud Run (see https://stackoverflow.com/a/55788899)

name: Build everything with Bazel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: gcloud auth configure-docker europe-central2-docker.pkg.dev
      - run: bazel build //...
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - run: bazel run :push_server
      - run: gcloud run deploy server --image europe-central2-docker.pkg.dev/alice-larp/bazel-test-drive/server:latest --region us-central1